version: '3'

services:
  postgres:
    image: habits-db
    restart: unless-stopped
    ports:
      - 7200:5432
    volumes:
      - storage:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  storage:
